# -*- coding: utf-8 -*-
"""Student Concentration Detection (Classification Problem - Computer Vision)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pC8k4ZlbnN1QKtHkRYxYWqMAWuw-s2sh
"""

from google.colab import drive
drive.mount('/content/drive')

#imports
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
import cv2
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay


import sys
import pandas as pd
from sklearn import metrics

test=cv2.imread('/content/drive/MyDrive/Anubrain assignment/Student-engagement-dataset/Engaged/confused/0021.jpg')

plt.imshow(cv2.cvtColor(test,cv2.COLOR_BGR2RGB))

faceCascade=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')

gray=cv2.cvtColor(test,cv2.COLOR_BGR2GRAY)
faces=faceCascade.detectMultiScale(gray,1.1,4)

x,y,w,h=faces[0]
plt.imshow(cv2.cvtColor(test[y:y+h,x:x+w],cv2.COLOR_BGR2RGB))

import os
import pandas as pd

def create_image_dataframe(data_dir):
    """
    Create a pandas DataFrame with image paths and corresponding class labels.

    Args:
        data_dir (str): The root directory containing subdirectories for each class.

    Returns:
        pd.DataFrame: A DataFrame with columns 'Image_Path' and 'Class_Label'.
    """
    image_paths = []
    class_labels = []

    # Walk through the directory and its subdirectories
    for class_label in os.listdir(data_dir):
        class_dir = os.path.join(data_dir, class_label)
        for subclass_label in os.listdir(class_dir):
          subclass_dir = os.path.join(class_dir, subclass_label)
          print(subclass_label)
          if os.path.isdir(subclass_dir):
              # Get a list of image files in the class directory
              images = [f for f in os.listdir(subclass_dir) if f.lower().endswith(('.jpg'))]

              # Add the image paths and class label to the lists
              image_paths.extend([os.path.join(subclass_dir, img) for img in images])
              class_labels.extend([str(class_label)+"_"+str(subclass_label)] * len(images))

    # Create a DataFrame
    image_df = pd.DataFrame({'Image_Path': image_paths, 'Class_Label': class_labels})

    return image_df

# Example usage:
data_directory = '/content/drive/MyDrive/Anubrain assignment/Student-engagement-dataset'
image_dataframe = create_image_dataframe(data_directory)
print(image_dataframe.head())

image_dataframe

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(image_dataframe, *['Class_Label'], **{})
chart

def process_imgs(image_path):
    """
    Process the img , crop the Face and convert it to grayscale

    Args:
        image_path (str): the img path

    Returns:
        np.array() : containing the img in grayscale
    """

    img=cv2.imread(image_path)
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faceCascade=cv2.CascadeClassifier(cv2.data.haarcascades+'haarcascade_frontalface_default.xml')
    faces=faceCascade.detectMultiScale(
        gray,  # Replace with your grayscale image
        scaleFactor=1.1,  # Adjust this value for trade-off between speed and accuracy
        minNeighbors=5,   # min of 5 overlapping rectangular
        minSize=(150, 150)  # Adjust this value for minimum object size
    )

    for x,y,w,h in faces:
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=img[y:y+h,x:x+w]
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2) #img with a rectangular on the face
        face_roi=roi_gray
        face_roi = cv2.resize(face_roi, (250, 250))
        return face_roi
    return cv2.resize(gray, (250, 250)) #if the face is not in frontal view (return the actual img (will need more time to deal with this))

def plot_images_in_row(images,titles, num_images=3, figsize=(15, 5)):
    """
    Plot multiple images in the same row.

    Args:
        images (list of numpy.ndarray): List of images to plot.
        titles (list of str, optional): List of titles for each image.
        num_images (int, optional): Number of images to show in the row.
        figsize (tuple, optional): Figure size (width, height).
    """
    num_images = min(num_images, len(images))
    fig, axes = plt.subplots(1, num_images, figsize=figsize)

    for i in range(num_images):
        axes[i].imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))
        axes[i].axis('off')

        if titles is not None and len(titles) > i:
            axes[i].set_title(titles[i])


    plt.show()

from tqdm import tqdm
tqdm.pandas()

img_data=image_dataframe['Image_Path'].apply(process_imgs)

Class_Label=image_dataframe['Class_Label']

image_dataframe['img_processed']=img_data

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
image_dataframe['Class_LabelEncoded'] = label_encoder.fit_transform(image_dataframe['Class_Label'])
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
label_mapping

image_dataframe

for i in range(0,424):
  plot_images_in_row(img_data[5*i:i*5+5].to_list(),Class_Label[5*i:i*5+5].to_list(),5)

import torch
from torch.utils.data import Dataset,DataLoader

class ImgDataset(Dataset):
    def __init__(self, df):
        self.Img_data = df.img_processed.to_list()
        self.labels = df.Class_LabelEncoded.to_list()

    def __len__(self):
        return len(self.Img_data)

    def __getitem__(self, idx):
        img = self.Img_data[idx]
        label = self.labels[idx]
        return img, label

#train test split
from sklearn.model_selection import train_test_split
# Perform the train-test split (80% train & 10% validation, 10% test )
X_train, X_testAndVal, y_train, y_testAndVal = train_test_split(image_dataframe, image_dataframe['Class_LabelEncoded'],stratify=image_dataframe['Class_LabelEncoded'], test_size=0.3, random_state=42)

X_val, X_test, y_val, y_test = train_test_split(X_testAndVal, X_testAndVal['Class_LabelEncoded'],stratify=X_testAndVal['Class_LabelEncoded'], test_size=0.2, random_state=42)

# Print the sizes of each split
print("Train set size:", len(X_train))
print("Validation set size:", len(X_val))
print("Test set size:", len(X_test))

image_dataframe['Class_LabelEncoded'].unique()

train_dataset = ImgDataset(X_train)
val_dataset = ImgDataset(X_val)
test_dataset = ImgDataset(X_test)

# Create a DataLoader from the dataset

train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_dataloader=DataLoader(val_dataset, batch_size=32, shuffle=True)
test_dataloader=DataLoader(test_dataset, batch_size=32, shuffle=False)

#change nn.sequential to take dict to make more readable
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms.functional as TF

class ParaNet(nn.Module):
    # Define all layers present in the network
    def __init__(self,num_emotions):
        super().__init__()
        self.dropout=nn.Dropout(p=0.3)
        self.relu=nn.ReLU()
        ############### 1ST PARALLEL 2D CONVOLUTION BLOCK ############
        # 3 sequential conv2D layers:
        self.conv2Dblock1 = nn.Sequential(

            # 1st 2D convolution layer
            nn.Conv2d(
                in_channels=1, # input volume depth == input channel dim == 1
                out_channels=16, # expand output feature map volume's depth to 16
                kernel_size=3, # typical 3*3 stride 1 kernel
                stride=1,
                padding=1
                      ),
            nn.BatchNorm2d(16), # batch normalize the output feature map before activation
            nn.ReLU(), # feature map --> activation map
            nn.MaxPool2d(kernel_size=2, stride=2), #typical maxpool kernel size
            nn.Dropout(p=0.4), #randomly zero 40% of 1st layer's output feature map in training

            # 2nd 2D convolution layer identical to last except output dim, maxpool kernel
            nn.Conv2d(
                in_channels=16,
                out_channels=32, # expand output feature map volume's depth to 32
                kernel_size=3,
                stride=1,
                padding=1
                      ),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=4, stride=4), # increase maxpool kernel for subsequent filters
            nn.Dropout(p=0.4),

            # 3rd 2D convolution layer identical to last except output dim
            nn.Conv2d(
                in_channels=32,
                out_channels=64, # expand output feature map volume's depth to 64
                kernel_size=3,
                stride=1,
                padding=1
                      ),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=4, stride=4),
            nn.Dropout(p=0.4),
        )
        ############### 2ND PARALLEL 2D CONVOLUTION BLOCK ############
        # 3 sequential conv2D layers:
        self.conv2Dblock2 = nn.Sequential(
            # 1st 2D convolution layer
            nn.Conv2d(
                in_channels=1, # input volume depth == input channel dim == 1
                out_channels=32, # expand output feature map volume's depth to 16
                kernel_size=3, # typical 3*3 stride 1 kernel
                stride=1,
                padding=1
                      ),
            nn.BatchNorm2d(32), # batch normalize the output feature map before activation
            nn.ReLU(), # feature map --> activation map
            nn.MaxPool2d(kernel_size=2, stride=2), #typical maxpool kernel size
            nn.Dropout(p=0.4), #randomly zero 40% of 1st layer's output feature map in training

            # 2nd 2D convolution layer identical to last except output dim, maxpool kernel
            nn.Conv2d(
                in_channels=32,
                out_channels=64, # expand output feature map volume's depth to 64
                kernel_size=5,
                stride=1,
                padding=2
                      ),
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=4, stride=4), # increase maxpool kernel for subsequent filters
            nn.Dropout(p=0.4),

            # 3rd 2D convolution layer identical to last except output dim
            nn.Conv2d(
                in_channels=64,
                out_channels=128, # expand output feature map volume's depth to 64
                kernel_size=7,
                stride=1,
                padding=3
                      ),
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=4, stride=4),
            nn.Dropout(p=0.4),
        )

        ################# FINAL LINEAR BLOCK ####################
        # Linear softmax layer to take final concatenated embedding tensor
        #    from parallel 2D convolutional and transformer blocks, output 6 logits

        self.fc1_linear = nn.Linear(9408,num_emotions)

        ### Softmax layer for the 6 output logits from final FC linear layer
        self.softmax_out = nn.Softmax(dim=1) # dim==1 is the freq embedding

    # define one complete parallel fwd pass of input feature tensor thru 2*conv+1*transformer blocks
    def forward(self,x):

        ############ 1st parallel Conv2D block: 4 Convolutional layers ############################
        # create final feature embedding from 1st convolutional layer
        # input features pased through 4 sequential 2D convolutional layers
        conv2d_embedding1 = self.conv2Dblock1(x) # x == N/batch * channel * freq * time
        conv2d_embedding1 = torch.flatten(conv2d_embedding1, start_dim=1)

        ############ 2nd parallel Conv2D block: 4 Convolutional layers #############################
        # create final feature embedding from 2nd convolutional layer
        conv2d_embedding2 = self.conv2Dblock2(x) # x == N/batch * channel * freq * time
        conv2d_embedding2 = torch.flatten(conv2d_embedding2, start_dim=1)



        complete_embedding = torch.cat([conv2d_embedding1, conv2d_embedding2], dim=1)
        ######### final FC linear layer, need logits for loss #########################
        output_logits = self.fc1_linear(complete_embedding)

        output_softmax = self.softmax_out(output_logits)

        # need output logits to compute cross entropy loss, need softmax probabilities to predict class
        return output_logits, output_softmax

import torch.optim as optim

EPOCHS=100
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
loss_fn =nn.CrossEntropyLoss().to(DEVICE)

LEARNING_RATE=1e-4
model = ParaNet(6).to(DEVICE)
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

def train_epoch(model, data_loader, loss_fn, optimizer, device):
    model = model.train()

    losses = []
    correct_predictions = 0
    total_predictions = 0

    for train_input, train_label in tqdm(data_loader):

        train_label = train_label.to(device)
        train_input = train_input.to(device)
        optimizer.zero_grad()

        output_logits, output_softmax = model(train_input.unsqueeze(1).float())
        predictions = torch.argmax(output_softmax,dim=1)
        total_predictions += train_label.size(0)

        correct_predictions += (predictions == train_label).sum().item()

        loss = loss_fn(output_logits, train_label)

        losses.append(loss.item())


        loss.backward()
        optimizer.step()

    print(f"Epoch {epoch+1}, Learning Rate: {optimizer.param_groups[0]['lr']}")

    accuracy = correct_predictions / total_predictions
    mean_loss = np.mean(losses)

    return mean_loss, accuracy

def eval_model(model, data_loader, loss_fn, device):
    model = model.eval()

    losses = []
    correct_predictions = 0
    total_predictions = 0

    with torch.no_grad():
        for val_input, val_label in data_loader:
            val_label = val_label.to(device)
            val_input = val_input.to(device)

            optimizer.zero_grad()

            output_logits, output_softmax = model(val_input.unsqueeze(1).float())

            predictions = torch.argmax(output_softmax,dim=1)
            total_predictions += val_label.size(0)

            correct_predictions += (predictions == val_label).sum().item()

            loss = loss_fn(output_logits, val_label)

            losses.append(loss.item())





        accuracy = correct_predictions / total_predictions
        mean_loss = np.mean(losses)


    return mean_loss, accuracy

from collections import defaultdict
import math
history = defaultdict(list)
loss=math.inf
epochs_without_improvement = 0
patience = 5  # Number of epochs to wait for improvement

for epoch in range(EPOCHS):


    train_loss,train_acc = train_epoch(model,train_dataloader,loss_fn, optimizer, DEVICE)

    val_loss,val_acc = eval_model(model,val_dataloader,loss_fn, DEVICE)


    print(f'Epoch {epoch + 1}/{EPOCHS}')
    print('-' * 10)
    print(f'Train loss {train_loss}')
    print(f'Train Accuracy {train_acc}')

    print(f'Val   loss {val_loss}')
    print(f'Val   Acc {val_acc}')

    print()

    if val_loss < loss:
        torch.save(model.state_dict(), 'best_model_state.bin')
        loss = val_loss
        epochs_without_improvement = 0
    else:
        epochs_without_improvement += 1

    # Early stopping condition
    if epochs_without_improvement == patience:
        print("Early stopping triggered. No improvement in", patience, "epochs.")
        break



    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)


    history['train_Accuracy'].append(train_acc)
    history['val_Accuracy'].append(val_acc)

    #save this incase of failure
    torch.save(model.state_dict(), 'current_model_state.bin')


#save last state to train later
torch.save(model.state_dict(), 'last_model_state.bin')

model.load_state_dict(torch.load('/content/best_model_state.bin'))

plt.plot(history['train_Accuracy'], label='train Accuracy')
plt.plot(history['val_Accuracy'], label='val Accuracy')

plt.title('Training history')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()

plt.plot(history['train_loss'], label='train_loss')
plt.plot(history['val_loss'], label='validation loss')

plt.title('Training history')
plt.ylabel('loss')
plt.xlabel('Epoch')
plt.legend()

def get_predicted(model, data_loader, loss_fn, device):
    model = model.eval()
    imgs=[]
    losses = []
    predicted_labels = []
    true_labels = []

    with torch.no_grad():
        for test_input, test_label in data_loader:
            test_label = test_label.to(device)
            test_input = test_input.to(device)
            imgs.append(test_input)
            output_logits, output_softmax = model(test_input.unsqueeze(1).float())

            predictions = torch.argmax(output_softmax, dim=1)
            predicted_labels.extend(predictions.cpu().numpy())
            true_labels.extend(test_label.cpu().numpy())

            loss = loss_fn(output_logits, test_label)
            losses.append(loss.item())

    mean_loss = np.mean(losses)

    return mean_loss, predicted_labels, true_labels,imgs

mean_loss, predicted_labels, true_labels,test_imgs=get_predicted(model,test_dataloader,loss_fn,DEVICE)

from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score,classification_report,confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
def measurements_of_accuracy(Y_test,Y_pred,classifier,labels):
    # Calculate the confusion matrix
    conf_matrix = confusion_matrix(y_true=Y_test, y_pred=Y_pred)
    matrix_precentage = conf_matrix.astype('float') / conf_matrix.sum(axis=1)[:, np.newaxis]

    fig, ax = plt.subplots(figsize=(5, 5))
    ax.matshow(conf_matrix, cmap=plt.cm.Oranges, alpha=0.3)
    for i in range(conf_matrix.shape[0]):
        for j in range(conf_matrix.shape[1]):
            ax.text(x=j, y=i,s=conf_matrix[i, j], va='center', ha='center')

    plt.xlabel('Predictions', fontsize=18)
    plt.ylabel('Actuals', fontsize=18)
    plt.title("Confusion Matrix for "+classifier+"Classifier", fontsize=18)
    plt.grid(False)
    plt.xticks(range(len(labels)), labels, rotation=90)  # Set x-axis labels
    plt.yticks(range(len(labels)), labels)  # Set y-axis labels
    plt.show()

    #Accuracy
    print('Accuracy : %.4f' % accuracy_score(Y_test, Y_pred))

    #precision score
    print('Precision : %.4f' % precision_score(Y_test, Y_pred,average='macro'))

    #Recall Score
    print('Recall : %.4f' % recall_score(Y_test, Y_pred,average='macro'))

    #F1 score
    print('F1 Score : %.4f' % f1_score(Y_test, Y_pred,average='macro'))

label_mapping

measurements_of_accuracy(true_labels,predicted_labels,"Confusion matrix",list(label_mapping.keys()))

inverted_dict = {v: k for k, v in label_mapping.items()}
inverted_dict

X_test.Class_LabelEncoded

predicted_list_labels=[inverted_dict[x] for x in predicted_labels]
predicted_list_labels

test_list=X_test.img_processed.to_list()
test_list_labels=X_test.Class_Label.to_list()

def plot_images_in_row_test(images, true_labels=None, predicted_labels=None, num_images=3, figsize=(15, 5)):
    num_images = min(num_images, len(images))
    fig, axes = plt.subplots(1, num_images, figsize=figsize)

    for i in range(num_images):
        axes[i].imshow(cv2.cvtColor(images[i], cv2.COLOR_BGR2RGB))
        axes[i].axis('off')

        # Add titles for true and predicted labels
        if true_labels is not None and len(true_labels) > i:
            true_label = true_labels[i]
        else:
            true_label = "True Label: N/A"

        if predicted_labels is not None and len(predicted_labels) > i:
            predicted_label = predicted_labels[i]
        else:
            predicted_label = "Predicted Label: N/A"

        title = f"{true_label}\n{predicted_label}"
        axes[i].set_title(title)

    plt.show()

# Example usage:

for i in range(0,32):
  plot_images_in_row_test(test_list[4*i:i*4+4],test_list_labels[4*i:i*4+4],predicted_list_labels[4*i:i*4+4],4)

incorrect_indices = [i for i in range(len(true_labels)) if true_labels[i] != predicted_labels[i]]
incorrect_indices

selected_elements_test = [test_list[i] for i in incorrect_indices]
selected_elements_test_labels = [test_list_labels[i] for i in incorrect_indices]
selected_predicted_test_labels = [predicted_list_labels[i] for i in incorrect_indices]

plot_images_in_row_test(selected_elements_test,selected_elements_test_labels,selected_predicted_test_labels,6)